-- create sequences
CREATE SEQUENCE hersteller_seq
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOCACHE;
  
CREATE SEQUENCE schaden_seq
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOCACHE;
  
CREATE SEQUENCE preisliste_seq
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOCACHE;
  
CREATE SEQUENCE status_seq
	MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOCACHE;
  
CREATE SEQUENCE adresse_seq
	MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOCACHE;
  
CREATE SEQUENCE standort_seq
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE SEQUENCE person_seq
	MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE SEQUENCE mitarbeiter_seq
	MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOCACHE;
  
CREATE SEQUENCE kunden_seq
	MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOCACHE;
  
CREATE SEQUENCE exemplar_seq
	MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOCACHE;
  
CREATE SEQUENCE verleih_seq
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOCACHE;
  
CREATE SEQUENCE exemp_schaden_seq
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE SEQUENCE auto_details_seq
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE SEQUENCE err_table_seq
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

