-- 1. Mahnungsansicht
-------------------------------------
CREATE OR REPLACE VIEW mahnungen_view
AS
SELECT KUNDE.KUNDE_ID AS kundennummer, PERSON.VORNAME, PERSON.NACHNAME, VERLEIH.VERLIEHEN_BIS, EXEMPLAR.KENNZEICHEN, HERSTELLER.BEZEICHNUNG, AUTO_DETAILS.MODELL_BESCHREIBUNG
FROM VERLEIH JOIN KUNDE ON KUNDE.KUNDE_ID = VERLEIH.KUNDE_ID
             JOIN PERSON ON KUNDE.PERSON_ID = PERSON.PERSON_ID
             JOIN EXEMPLAR ON EXEMPLAR.EXEMPLAR_ID = VERLEIH.EXEMPLAR_ID
             JOIN AUTO_DETAILS ON AUTO_DETAILS.DETAIL_ID = EXEMPLAR.AUTO_DETAILS_ID
             JOIN HERSTELLER ON HERSTELLER.HERSTELLER_ID = AUTO_DETAILS.HERSTELLER_ID
WHERE RETOURNIERT = 0 AND
      VERLIEHEN_BIS < SYSDATE;
-------------------------------------

-- 2. Verfügbare Autos anzeigen (Hauptsandort)
-------------------------------------
CREATE OR REPLACE VIEW autos_hauptstandort_view
AS
SELECT EXEMPLAR.EXEMPLAR_ID, EXEMPLAR.FARBE, EXEMPLAR.ERSTZULASSUNG, HERSTELLER.BEZEICHNUNG, AUTO_DETAILS.MODELL_BESCHREIBUNG, AUTO_DETAILS.PS, AUTO_DETAILS.VERBRAUCH, AUTO_DETAILS.SITZPLAETZE, PREISLISTE.KOSTEN_PRO_TAG
FROM EXEMPLAR JOIN AUTO_DETAILS ON AUTO_DETAILS.DETAIL_ID = EXEMPLAR.AUTO_DETAILS_ID
              JOIN HERSTELLER ON HERSTELLER.HERSTELLER_ID = AUTO_DETAILS.HERSTELLER_ID
              JOIN PREISLISTE ON PREISLISTE.PREIS_ID = AUTO_DETAILS.PREIS_ID
WHERE STANDORT_ID = 1 AND
      EXEMPLAR.SCHAEDEN_ID IS NULL AND
      EXEMPLAR.STATUS_ID = 2;
-------------------------------------

-- 3. Alle Autos mit Details und Preis pro Tag anzeigen
-------------------------------------
CREATE OR REPLACE VIEW verfuegbare_autos_view
AS
SELECT EXEMPLAR.EXEMPLAR_ID, EXEMPLAR.ERSTZULASSUNG, EXEMPLAR.FARBE, HERSTELLER.BEZEICHNUNG, AUTO_DETAILS.MODELL_BESCHREIBUNG, AUTO_DETAILS.PS, AUTO_DETAILS.SITZPLAETZE, AUTO_DETAILS.VERBRAUCH, PREISLISTE.KOSTEN_PRO_TAG, STANDORT.BEZEICHNUNG AS STANDORT, ADRESSE.STRASSE || ' ' || ADRESSE.HAUSNUMMER AS adresse, POSTLEITZAHL.PLZ, POSTLEITZAHL.ORTSNAME
FROM EXEMPLAR JOIN AUTO_DETAILS ON AUTO_DETAILS.DETAIL_ID = EXEMPLAR.AUTO_DETAILS_ID
              JOIN HERSTELLER ON HERSTELLER.HERSTELLER_ID = AUTO_DETAILS.HERSTELLER_ID
              JOIN PREISLISTE ON PREISLISTE.PREIS_ID = AUTO_DETAILS.PREIS_ID
              JOIN STANDORT ON STANDORT.STANDORT_ID = EXEMPLAR.STANDORT_ID
              JOIN ADRESSE ON STANDORT.ADRESS_ID = ADRESSE.ADRESS_ID
              JOIN POSTLEITZAHL ON ADRESSE.PLZ = POSTLEITZAHL.PLZ
WHERE EXEMPLAR.SCHAEDEN_ID IS NULL AND
      EXEMPLAR.STATUS_ID = 2;
-------------------------------------

-- 4. Beschädigte Autos anzeigen
-------------------------------------
CREATE OR REPLACE VIEW auto_schaeden_view
AS
SELECT EXEMPLAR.EXEMPLAR_ID, EXEMPLAR.KENNZEICHEN, HERSTELLER.BEZEICHNUNG || ' ' || AUTO_DETAILS.MODELL_BESCHREIBUNG AS modell, SCHAEDEN.BESCHREIBUNG, STANDORT.BEZEICHNUNG AS STANDORT
FROM EXEMP_SCHAEDEN JOIN EXEMPLAR ON EXEMPLAR.EXEMPLAR_ID = EXEMP_SCHAEDEN.EXEMPLAR_ID
                    JOIN SCHAEDEN ON SCHAEDEN.SCHAEDEN_ID = EXEMPLAR.SCHAEDEN_ID
                    JOIN AUTO_DETAILS ON AUTO_DETAILS.DETAIL_ID = EXEMPLAR.AUTO_DETAILS_ID
                    JOIN HERSTELLER ON HERSTELLER.HERSTELLER_ID = AUTO_DETAILS.HERSTELLER_ID
                    JOIN STANDORT ON STANDORT.STANDORT_ID = EXEMPLAR.STANDORT_ID;
-------------------------------------

-- 5. Kundendaten anzeigen
-------------------------------------
CREATE OR REPLACE VIEW kundendaten_view
AS
SELECT KUNDE.KUNDE_ID AS KUNDENNUMMER, PERSON.VORNAME, PERSON.NACHNAME, PERSON.GEBURTSTDATUM, ADRESSE.STRASSE, ADRESSE.HAUSNUMMER, ADRESSE.TUERNUMMER, POSTLEITZAHL.PLZ, POSTLEITZAHL.ORTSNAME
FROM KUNDE JOIN PERSON ON KUNDE.PERSON_ID = PERSON.PERSON_ID
           JOIN ADRESSE ON ADRESSE.ADRESS_ID = PERSON.ADRESS_ID
           JOIN POSTLEITZAHL ON ADRESSE.PLZ = POSTLEITZAHL.PLZ;
-------------------------------------
