--DROP DA TABLES; DROP DA MIC!
DROP TABLE HERSTELLER CASCADE CONSTRAINTS;
DROP TABLE VERLEIH CASCADE CONSTRAINTS;
DROP TABLE EXEMPLAR CASCADE CONSTRAINTS;
DROP TABLE EXEMP_SCHAEDEN CASCADE CONSTRAINTS;
DROP TABLE SCHAEDEN CASCADE CONSTRAINTS;
DROP TABLE STATUS CASCADE CONSTRAINTS;
DROP TABLE PREISLISTE CASCADE CONSTRAINTS;
DROP TABLE AUTO_DETAILS CASCADE CONSTRAINTS;
DROP TABLE PERSON CASCADE CONSTRAINTS;
DROP TABLE MITARBEITER CASCADE CONSTRAINTS;
DROP TABLE KUNDE CASCADE CONSTRAINTS;
DROP TABLE ADRESSE CASCADE CONSTRAINTS;
DROP TABLE STANDORT CASCADE CONSTRAINTS;
DROP TABLE POSTLEITZAHL CASCADE CONSTRAINTS;
DROP TABLE ERR_TABLE CASCADE CONSTRAINTS;
