-- drop view
DROP VIEW MAHNUNGEN_VIEW;
DROP VIEW AUTOS_HAUPTSTANDORT_VIEW;
DROP VIEW VERFUEGBARE_AUTOS_VIEW;
DROP VIEW KUNDENDATEN_VIEW;
DROP VIEW AUTO_SCHAEDEN_VIEW;
DROP VIEW RECHNUNGEN_VIEW;

COMMIT;