-- Insert Hersteller --
INSERT INTO HERSTELLER (HERSTELLER_ID, BEZEICHNUNG) VALUES (hersteller_seq.NEXTVAL, 'Mercedes');			
INSERT INTO HERSTELLER (HERSTELLER_ID, BEZEICHNUNG) VALUES (hersteller_seq.NEXTVAL, 'VW');			
INSERT INTO HERSTELLER (HERSTELLER_ID, BEZEICHNUNG) VALUES (hersteller_seq.NEXTVAL, 'BMW');		
INSERT INTO HERSTELLER (HERSTELLER_ID, BEZEICHNUNG) VALUES (hersteller_seq.NEXTVAL, 'Ford');		
INSERT INTO HERSTELLER (HERSTELLER_ID, BEZEICHNUNG) VALUES (hersteller_seq.NEXTVAL, 'Alfa Romeo');		
INSERT INTO HERSTELLER (HERSTELLER_ID, BEZEICHNUNG) VALUES (hersteller_seq.NEXTVAL, 'Ferrari');

-- Insert PLZ --			
INSERT INTO POSTLEITZAHL ("PLZ", "ORTSNAME") VALUES (1010, 'WIEN');
INSERT INTO POSTLEITZAHL ("PLZ", "ORTSNAME") VALUES (1020, 'WIEN');
INSERT INTO POSTLEITZAHL ("PLZ", "ORTSNAME") VALUES (1030, 'WIEN');
INSERT INTO POSTLEITZAHL ("PLZ", "ORTSNAME") VALUES (1040, 'WIEN');
INSERT INTO POSTLEITZAHL ("PLZ", "ORTSNAME") VALUES (1050, 'WIEN');
INSERT INTO POSTLEITZAHL ("PLZ", "ORTSNAME") VALUES (1060, 'WIEN');
INSERT INTO POSTLEITZAHL ("PLZ", "ORTSNAME") VALUES (1070, 'WIEN');
INSERT INTO POSTLEITZAHL ("PLZ", "ORTSNAME") VALUES (1080, 'WIEN');
INSERT INTO POSTLEITZAHL ("PLZ", "ORTSNAME") VALUES (1090, 'WIEN');
INSERT INTO POSTLEITZAHL ("PLZ", "ORTSNAME") VALUES (1100, 'WIEN');
INSERT INTO POSTLEITZAHL ("PLZ", "ORTSNAME") VALUES (1110, 'WIEN');
INSERT INTO POSTLEITZAHL ("PLZ", "ORTSNAME") VALUES (1120, 'WIEN');
INSERT INTO POSTLEITZAHL ("PLZ", "ORTSNAME") VALUES (1130, 'WIEN');
INSERT INTO POSTLEITZAHL ("PLZ", "ORTSNAME") VALUES (1140, 'WIEN');
INSERT INTO POSTLEITZAHL ("PLZ", "ORTSNAME") VALUES (1150, 'WIEN');
INSERT INTO POSTLEITZAHL ("PLZ", "ORTSNAME") VALUES (1160, 'WIEN');
INSERT INTO POSTLEITZAHL ("PLZ", "ORTSNAME") VALUES (1170, 'WIEN');
INSERT INTO POSTLEITZAHL ("PLZ", "ORTSNAME") VALUES (1180, 'WIEN');
INSERT INTO POSTLEITZAHL ("PLZ", "ORTSNAME") VALUES (1190, 'WIEN');
INSERT INTO POSTLEITZAHL ("PLZ", "ORTSNAME") VALUES (1200, 'WIEN');
INSERT INTO POSTLEITZAHL ("PLZ", "ORTSNAME") VALUES (1210, 'WIEN');
INSERT INTO POSTLEITZAHL ("PLZ", "ORTSNAME") VALUES (1220, 'WIEN');
INSERT INTO POSTLEITZAHL ("PLZ", "ORTSNAME") VALUES (1230, 'WIEN');

-- Insert Schaeden --
INSERT INTO SCHAEDEN (SCHAEDEN_ID, BESCHREIBUNG) VALUES (schaden_seq.NEXTVAL, 'Motorschaden');
INSERT INTO SCHAEDEN (SCHAEDEN_ID, BESCHREIBUNG) VALUES (schaden_seq.NEXTVAL, 'Totalschaden');
INSERT INTO SCHAEDEN (SCHAEDEN_ID, BESCHREIBUNG) VALUES (schaden_seq.NEXTVAL, 'Keine Scheibenwischfluessigkeit');
INSERT INTO SCHAEDEN (SCHAEDEN_ID, BESCHREIBUNG) VALUES (schaden_seq.NEXTVAL, 'Leichte Dellen');
INSERT INTO SCHAEDEN (SCHAEDEN_ID, BESCHREIBUNG) VALUES (schaden_seq.NEXTVAL, 'Oelstand pruefen');

-- Insert Preisliste --
INSERT INTO PREISLISTE (PREIS_ID, KOSTEN_PRO_TAG) VALUES (preisliste_seq.NEXTVAL, 42);
INSERT INTO PREISLISTE (PREIS_ID, KOSTEN_PRO_TAG) VALUES (preisliste_seq.NEXTVAL, 8);
INSERT INTO PREISLISTE (PREIS_ID, KOSTEN_PRO_TAG) VALUES (preisliste_seq.NEXTVAL, 22);
INSERT INTO PREISLISTE (PREIS_ID, KOSTEN_PRO_TAG) VALUES (preisliste_seq.NEXTVAL, 98);
INSERT INTO PREISLISTE (PREIS_ID, KOSTEN_PRO_TAG) VALUES (preisliste_seq.NEXTVAL, 14);
INSERT INTO PREISLISTE (PREIS_ID, KOSTEN_PRO_TAG) VALUES (preisliste_seq.NEXTVAL, 18);

-- Insert Status --
INSERT INTO STATUS (STATUS_ID, BESCHREIBUNG) VALUES (status_seq.NEXTVAL, 'Verliehen');
INSERT INTO STATUS (STATUS_ID, BESCHREIBUNG) VALUES (status_seq.NEXTVAL, 'Im Haus');
INSERT INTO STATUS (STATUS_ID, BESCHREIBUNG) VALUES (status_seq.NEXTVAL, 'Kaputt');
INSERT INTO STATUS (STATUS_ID, BESCHREIBUNG) VALUES (status_seq.NEXTVAL, 'Bestellt');

-- Insert Adresse --
INSERT INTO ADRESSE (ADRESS_ID, STRASSE, HAUSNUMMER, TUERNUMMER, PLZ) VALUES (adresse_seq.NEXTVAL, 'Hafenstrasse', 10, 1, 1210);
INSERT INTO ADRESSE (ADRESS_ID, STRASSE, HAUSNUMMER, TUERNUMMER, PLZ) VALUES (adresse_seq.NEXTVAL, 'GuentherJauchStrasse', 18, 1, 1080);
INSERT INTO ADRESSE (ADRESS_ID, STRASSE, HAUSNUMMER, TUERNUMMER, PLZ) VALUES (adresse_seq.NEXTVAL, 'FriedrichManhartsstrasse', 3, 42, 1230);
INSERT INTO ADRESSE (ADRESS_ID, STRASSE, HAUSNUMMER, TUERNUMMER, PLZ) VALUES (adresse_seq.NEXTVAL, 'Hanreitergasse', 10, 13, 1040);
INSERT INTO ADRESSE (ADRESS_ID, STRASSE, HAUSNUMMER, TUERNUMMER, PLZ) VALUES (adresse_seq.NEXTVAL, 'Suedtirolerplatz', 156, 87, 1110);
INSERT INTO ADRESSE (ADRESS_ID, STRASSE, HAUSNUMMER, TUERNUMMER, PLZ) VALUES (adresse_seq.NEXTVAL, 'Ringstrasse', 3, 1, 1010);

-- Insert Standorte --
INSERT INTO STANDORT (STANDORT_ID, BEZEICHNUNG, ADRESS_ID) VALUES (standort_seq.NEXTVAL, 'Hauptstandort', 1);
INSERT INTO STANDORT (STANDORT_ID, BEZEICHNUNG, ADRESS_ID) VALUES (standort_seq.NEXTVAL, 'Nebenstandort', 6);

-- Insert Personen --
INSERT INTO PERSON (PERSON_ID, VORNAME, NACHNAME, GEBURTSTDATUM, ADRESSE_ID) VALUES (person_seq.NEXTVAL, 'Max', 'Mustermann', TO_DATE( '04/04/1997 13:35', 'DD/MM/YYYY HH24:MI' ),1);
INSERT INTO PERSON (PERSON_ID, VORNAME, NACHNAME, GEBURTSTDATUM, ADRESSE_ID) VALUES (person_seq.NEXTVAL, 'John', 'Doe', TO_DATE( '04/06/1988 13:35', 'DD/MM/YYYY HH24:MI' ),1);
INSERT INTO PERSON (PERSON_ID, VORNAME, NACHNAME, GEBURTSTDATUM, ADRESSE_ID) VALUES (person_seq.NEXTVAL, 'Max', 'Mann', TO_DATE( '21/11/2002 13:05', 'DD/MM/YYYY HH24:MI' ),2);
INSERT INTO PERSON (PERSON_ID, VORNAME, NACHNAME, GEBURTSTDATUM, ADRESSE_ID) VALUES (person_seq.NEXTVAL, 'Tom', 'Turbo', TO_DATE( '14/12/1965 15:14', 'DD/MM/YYYY HH24:MI' ),3);
INSERT INTO PERSON (PERSON_ID, VORNAME, NACHNAME, GEBURTSTDATUM, ADRESSE_ID) VALUES (person_seq.NEXTVAL, 'Jane', 'Doe', TO_DATE( '22/02/1956 16:29', 'DD/MM/YYYY HH24:MI' ),4);
INSERT INTO PERSON (PERSON_ID, VORNAME, NACHNAME, GEBURTSTDATUM, ADRESSE_ID) VALUES (person_seq.NEXTVAL, 'Mary', 'Jane', TO_DATE( '18/06/1977 19:45', 'DD/MM/YYYY HH24:MI' ),5);
INSERT INTO PERSON (PERSON_ID, VORNAME, NACHNAME, GEBURTSTDATUM, ADRESSE_ID) VALUES (person_seq.NEXTVAL, 'Susanne', 'Gruber', TO_DATE( '23/07/1943 10:57', 'DD/MM/YYYY HH24:MI' ),6);
INSERT INTO PERSON (PERSON_ID, VORNAME, NACHNAME, GEBURTSTDATUM, ADRESSE_ID) VALUES (person_seq.NEXTVAL, 'Hannah', 'Karpfen', TO_DATE( '29/04/1999 09:15', 'DD/MM/YYYY HH24:MI' ),1);

-- Insert Mitarbeiter --
INSERT INTO MITARBEITER (MITARBEITER_ID, PERSON_ID, STANDORT_ID) VALUES (mitarbeiter_seq.NEXTVAL, 2, 1);
INSERT INTO MITARBEITER (MITARBEITER_ID, PERSON_ID, STANDORT_ID) VALUES (mitarbeiter_seq.NEXTVAL, 5, 1);
INSERT INTO MITARBEITER (MITARBEITER_ID, PERSON_ID, STANDORT_ID) VALUES (mitarbeiter_seq.NEXTVAL, 1, 2);

-- Insert Kunde --
INSERT INTO  KUNDE (KUNDEN_ID, PERSON_ID) VALUES (kunden_seq.NEXTVAL, 3);
INSERT INTO  KUNDE (KUNDEN_ID, PERSON_ID) VALUES (kunden_seq.NEXTVAL, 4);
INSERT INTO  KUNDE (KUNDEN_ID, PERSON_ID) VALUES (kunden_seq.NEXTVAL, 6);
INSERT INTO  KUNDE (KUNDEN_ID, PERSON_ID) VALUES (kunden_seq.NEXTVAL, 7);
INSERT INTO  KUNDE (KUNDEN_ID, PERSON_ID) VALUES (kunden_seq.NEXTVAL, 8);

-- Insert Auto_Detail --
INSERT INTO AUTO_DETAILS (DETAIL_ID, MODELL_BESCHREIBUNG, SITZPLAETZE, VERBRAUCH, PS, PREIS_ID, HERSTELLER_ID) VALUES(auto_details_seq.NEXTVAL, 'AMG GT 63 S', 4, 113, 639, 4, 1);
INSERT INTO AUTO_DETAILS (DETAIL_ID, MODELL_BESCHREIBUNG, SITZPLAETZE, VERBRAUCH, PS, PREIS_ID, HERSTELLER_ID) VALUES(auto_details_seq.NEXTVAL, 'F40', 2, 11.8, 471, 4, 6);
INSERT INTO AUTO_DETAILS (DETAIL_ID, MODELL_BESCHREIBUNG, SITZPLAETZE, VERBRAUCH, PS, PREIS_ID, HERSTELLER_ID) VALUES(auto_details_seq.NEXTVAL, 'Golf 1 GTI', 4, 8.8, 110, 2, 2);
INSERT INTO AUTO_DETAILS (DETAIL_ID, MODELL_BESCHREIBUNG, SITZPLAETZE, VERBRAUCH, PS, PREIS_ID, HERSTELLER_ID) VALUES(auto_details_seq.NEXTVAL, '2er Coupe', 5, 7.1, 220, 2, 3);
INSERT INTO AUTO_DETAILS (DETAIL_ID, MODELL_BESCHREIBUNG, SITZPLAETZE, VERBRAUCH, PS, PREIS_ID, HERSTELLER_ID) VALUES(auto_details_seq.NEXTVAL, 'Golf Variant', 5, 5.5, 114, 6, 2);
INSERT INTO AUTO_DETAILS (DETAIL_ID, MODELL_BESCHREIBUNG, SITZPLAETZE, VERBRAUCH, PS, PREIS_ID, HERSTELLER_ID) VALUES(auto_details_seq.NEXTVAL, 'Mustang 289', 2, 10, 203, 4, 4);
INSERT INTO AUTO_DETAILS (DETAIL_ID, MODELL_BESCHREIBUNG, SITZPLAETZE, VERBRAUCH, PS, PREIS_ID, HERSTELLER_ID) VALUES(auto_details_seq.NEXTVAL, 'Giulietta', 5, 6.9, 124, 3, 5);

-- Insert Exemplar --
INSERT INTO EXEMPLAR (EXEMPLAR_ID, KENNZEICHEN, ERSTZULASSUNG, FARBE, STATUS_ID, SCHAEDEN_ID, STANDORT_ID, AUTO_DETAILS_ID) VALUES (exemplar_seq.NEXTVAL, 'Wabcd01', TO_DATE('29/01/1999 09:15', 'DD/MM/YYYY HH24:MI'), 'Blau', 3, 1, 1, 1);
INSERT INTO EXEMPLAR (EXEMPLAR_ID, KENNZEICHEN, ERSTZULASSUNG, FARBE, STATUS_ID, STANDORT_ID, AUTO_DETAILS_ID) VALUES (exemplar_seq.NEXTVAL, 'Wabcd02', TO_DATE('19/10/2005 09:15', 'DD/MM/YYYY HH24:MI'), 'Schwarz', 1, 1, 2);
INSERT INTO EXEMPLAR (EXEMPLAR_ID, KENNZEICHEN, ERSTZULASSUNG, FARBE, STATUS_ID, STANDORT_ID, AUTO_DETAILS_ID) VALUES (exemplar_seq.NEXTVAL, 'Wabcd03', TO_DATE('25/04/1992 09:15', 'DD/MM/YYYY HH24:MI'), 'Schwarz', 1, 2, 3);
INSERT INTO EXEMPLAR (EXEMPLAR_ID, KENNZEICHEN, ERSTZULASSUNG, FARBE, STATUS_ID, STANDORT_ID, AUTO_DETAILS_ID) VALUES (exemplar_seq.NEXTVAL, 'Wabcd04', TO_DATE('11/06/2019 09:15', 'DD/MM/YYYY HH24:MI'), 'Silber', 1, 1, 4);
INSERT INTO EXEMPLAR (EXEMPLAR_ID, KENNZEICHEN, ERSTZULASSUNG, FARBE, STATUS_ID, STANDORT_ID, AUTO_DETAILS_ID) VALUES (exemplar_seq.NEXTVAL, 'Wabcd05', TO_DATE('04/09/2014 09:15', 'DD/MM/YYYY HH24:MI'), 'Gruen', 2, 2, 5);

-- Insert Verleih --
INSERT INTO VERLEIH (VERLEIH_ID, EXEMPLAR_ID, KUNDE_ID, VERLIEHEN_AB, VERLIEHEN_BIS, RETOURNIERT, MITARBEITER_ID) VALUES (verleih_seq.NEXTVAL, 1, 1, TO_DATE('19/11/2019 09:15', 'DD/MM/YYYY HH24:MI'), TO_DATE('23/12/1219 09:15', 'DD/MM/YYYY HH24:MI'), 0, 1);
INSERT INTO VERLEIH (VERLEIH_ID, EXEMPLAR_ID, KUNDE_ID, VERLIEHEN_AB, VERLIEHEN_BIS, RETOURNIERT, MITARBEITER_ID) VALUES (verleih_seq.NEXTVAL, 2, 2, TO_DATE('29/05/2019 09:15', 'DD/MM/YYYY HH24:MI'), TO_DATE('15/06/1219 09:15', 'DD/MM/YYYY HH24:MI'), 1, 1);
INSERT INTO VERLEIH (VERLEIH_ID, EXEMPLAR_ID, KUNDE_ID, VERLIEHEN_AB, VERLIEHEN_BIS, RETOURNIERT, MITARBEITER_ID) VALUES (verleih_seq.NEXTVAL, 3, 3, TO_DATE('18/07/2019 09:15', 'DD/MM/YYYY HH24:MI'), TO_DATE('23/12/1219 09:15', 'DD/MM/YYYY HH24:MI'), 0, 2);
INSERT INTO VERLEIH (VERLEIH_ID, EXEMPLAR_ID, KUNDE_ID, VERLIEHEN_AB, VERLIEHEN_BIS, RETOURNIERT, MITARBEITER_ID) VALUES (verleih_seq.NEXTVAL, 4, 4, TO_DATE('22/04/2019 09:15', 'DD/MM/YYYY HH24:MI'), TO_DATE('29/10/1219 09:15', 'DD/MM/YYYY HH24:MI'), 0, 2);
INSERT INTO VERLEIH (VERLEIH_ID, EXEMPLAR_ID, KUNDE_ID, VERLIEHEN_AB, VERLIEHEN_BIS, RETOURNIERT, MITARBEITER_ID) VALUES (verleih_seq.NEXTVAL, 5, 5, TO_DATE('01/01/2019 09:15', 'DD/MM/YYYY HH24:MI'), TO_DATE('01/09/1219 09:15', 'DD/MM/YYYY HH24:MI'), 0, 3);

-- Insert Exemp Schaden --
INSERT INTO EXEMP_SCHAEDEN (KOMBO_ID, SCHAEDEN_ID, EXEMPLAR_ID) VALUES (exemp_schaden_seq.NEXTVAL, 1, 1);
