/*********************************************************************
/**
/** Table: verfuegbare_autos_view
/** Developer: 
/** Description: Beinhaltet alle Autos am Haupt- und Nebenstandort
/**
/*********************************************************************/
CREATE OR REPLACE VIEW verfuegbare_autos_view
AS
SELECT EXEMPLAR.EXEMPLAR_ID, 
       EXEMPLAR.ERSTZULASSUNG, 
       EXEMPLAR.FARBE, 
       HERSTELLER.BEZEICHNUNG, 
       AUTO_DETAILS.MODELL_BESCHREIBUNG, 
       AUTO_DETAILS.PS, 
       AUTO_DETAILS.SITZPLAETZE, 
       AUTO_DETAILS.VERBRAUCH, 
       PREISLISTE.KOSTEN_PRO_TAG, 
       STANDORT.BEZEICHNUNG AS STANDORT, 
       ADRESSE.STRASSE || ' ' || ADRESSE.HAUSNUMMER AS adresse, 
       POSTLEITZAHL.PLZ, 
       POSTLEITZAHL.ORTSNAME
FROM EXEMPLAR JOIN AUTO_DETAILS ON AUTO_DETAILS.DETAIL_ID = EXEMPLAR.AUTO_DETAILS_ID
              JOIN HERSTELLER ON HERSTELLER.HERSTELLER_ID = AUTO_DETAILS.HERSTELLER_ID
              JOIN PREISLISTE ON PREISLISTE.PREIS_ID = AUTO_DETAILS.PREIS_ID
              JOIN STANDORT ON STANDORT.STANDORT_ID = EXEMPLAR.STANDORT_ID
              JOIN ADRESSE ON STANDORT.ADRESS_ID = ADRESSE.ADRESS_ID
              JOIN POSTLEITZAHL ON ADRESSE.PLZ = POSTLEITZAHL.PLZ
WHERE EXEMPLAR.SCHAEDEN_ID IS NULL AND
      EXEMPLAR.STATUS_ID = 2;

COMMIT;