/*********************************************************************
/**
/** Table: rechnungen_view
/** Developer: 
/** Description: Zeigt alle Rechnungen an
/**
/*********************************************************************/
CREATE OR REPLACE VIEW rechnungen_view
AS
SELECT VERLEIH.VERLEIH_ID, 
       EXEMPLAR.EXEMPLAR_ID, 
       KUNDE.KUNDE_ID, 
       PERSON.VORNAME, 
       PERSON.NACHNAME, 
       VERLEIH.MITARBEITER_ID, 
       HERSTELLER.BEZEICHNUNG, 
       AUTO_DETAILS.MODELL_BESCHREIBUNG, 
       CAST(VERLEIH.VERLIEHEN_BIS AS DATE) - CAST(VERLEIH.VERLIEHEN_AB AS DATE) AS dauer, 
       PREISLISTE.KOSTEN_PRO_TAG, 
       PREISLISTE.KOSTEN_PRO_TAG * CAST(CAST(VERLEIH.VERLIEHEN_BIS AS DATE) - CAST(VERLEIH.VERLIEHEN_AB AS DATE) AS NUMBER) AS kosten_insgesamt, 
       VERLEIH.RETOURNIERT as bezahlt
FROM VERLEIH JOIN KUNDE ON KUNDE.KUNDE_ID = VERLEIH.KUNDE_ID
             JOIN PERSON ON KUNDE.PERSON_ID = PERSON.PERSON_ID
             JOIN ADRESSE ON ADRESSE.ADRESS_ID = PERSON.ADRESS_ID             
             JOIN EXEMPLAR ON EXEMPLAR.EXEMPLAR_ID = VERLEIH.EXEMPLAR_ID
             JOIN AUTO_DETAILS ON AUTO_DETAILS.DETAIL_ID = EXEMPLAR.AUTO_DETAILS_ID
             JOIN HERSTELLER ON HERSTELLER.HERSTELLER_ID = AUTO_DETAILS.HERSTELLER_ID
             JOIN PREISLISTE ON PREISLISTE.PREIS_ID = AUTO_DETAILS.PREIS_ID;

COMMIT;
