-- Kunden anpassen
--------------------------------------
/*
 * Rechnung benötigt:
 * Kunden: Nummer, Vorname, Nachname, Adresse
 * Mitarbeiter: Nummer
 * Auto_Details: Bezeichnung, Preis
 * Hersteller: Bezeichnung
 * Verleih: Preis, Dauer
 * Preisliste: Preis pro Tag
*/

SELECT * FROM KUNDE;
SELECT * FROM PERSON;
SELECT * FROM ADRESSE;
SELECT * FROM POSTLEITZAHL;
SELECT * FROM EXEMPLAR;
SELECT * FROM AUTO_DETAILS;
SELECT * FROM HERSTELLER;
SELECT * FROM VERLEIH;
SELECT * FROM PREISLISTE;

-- 'Rechnung' ausgeben
SELECT VERLEIH.VERLEIH_ID, KUNDE.KUNDE_ID, PERSON.VORNAME, PERSON.NACHNAME, VERLEIH.MITARBEITER_ID, HERSTELLER.BEZEICHNUNG, AUTO_DETAILS.MODELL_BESCHREIBUNG, CAST(VERLEIH.VERLIEHEN_BIS AS DATE) - CAST(VERLEIH.VERLIEHEN_AB AS DATE) AS dauer, PREISLISTE.KOSTEN_PRO_TAG, PREISLISTE.KOSTEN_PRO_TAG * CAST(CAST(VERLEIH.VERLIEHEN_BIS AS DATE) - CAST(VERLEIH.VERLIEHEN_AB AS DATE) AS NUMBER) AS kosten_insgesamt
FROM VERLEIH JOIN KUNDE ON KUNDE.KUNDE_ID = VERLEIH.KUNDE_ID
             JOIN PERSON ON KUNDE.PERSON_ID = PERSON.PERSON_ID
             JOIN ADRESSE ON ADRESSE.ADRESS_ID = PERSON.ADRESS_ID             
             JOIN EXEMPLAR ON EXEMPLAR.EXEMPLAR_ID = VERLEIH.EXEMPLAR_ID
             JOIN AUTO_DETAILS ON AUTO_DETAILS.DETAIL_ID = EXEMPLAR.AUTO_DETAILS_ID
             JOIN HERSTELLER ON HERSTELLER.HERSTELLER_ID = AUTO_DETAILS.HERSTELLER_ID
             JOIN PREISLISTE ON PREISLISTE.PREIS_ID = AUTO_DETAILS.PREIS_ID;
